
package gui;

import controller.StudentController;
import dao.MinitryDAO;
import dao.StudentDAO;
import pojo.MinitryEntity;
import pojo.StudentEntity;

import javax.swing.*;
import java.awt.*;
import java.sql.Date;


public class jPnQLGV extends javax.swing.JPanel {

    /**
     * Creates new form jPnQLGV
     */
    public jPnQLGV() {
        initComponents();
        setData();
    }

    public void setData() {
        btnDelete.setEnabled(false);
        btnReset.setEnabled(false);
        btnEdit.setEnabled(false);
        StudentController controller = new StudentController(jPnTable, jTFSearch);
        controller.setDataToTableMinitry();
        controller.setButton(btnDelete, btnReset, btnEdit, jTFUserame, jTFName, jBCgender, jTAadd, jDCbirth,labelId);
        jTFUserame.requestFocus();
        labelId.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        labelId= new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAadd = new javax.swing.JTextArea();
        jTFUserame = new javax.swing.JTextField();
        jTFName = new javax.swing.JTextField();
        jBCgender = new javax.swing.JComboBox<>();
        jDCbirth = new com.toedter.calendar.JDateChooser();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFSearch = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jPnTable = new javax.swing.JPanel();

        jLabel2.setFont(new java.awt.Font("Tahoma",0, 14)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên:");
        labelId.setVisible(false);
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Giới tính:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        jTAadd.setColumns(20);
        jTAadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTAadd.setRows(5);
        jScrollPane1.setViewportView(jTAadd);

        jTFUserame.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFUserame.setToolTipText("");
        jTFUserame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFUsernameKeyReleased(evt);
            }
        });


        jTFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNameKeyReleased(evt);
            }
        });


        jBCgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Nữ", "Nam"}));
        jBCgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCgenderActionPerformed(evt);
            }
        });
        jBCgender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBCgenderKeyReleased(evt);
            }
        });


        jDCbirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDCbirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDCbirthKeyReleased(evt);
            }
        });


        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("Cập nhật");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rotate-left-circular-arrow-interface-symbol.png"))); // NOI18N
        btnReset.setText("Reset pass");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-search.png"))); // NOI18N

        jTFSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFSearch.setToolTipText("Tìm kiếm");
        jTFSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSearchActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jDCbirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addContainerGap(121, Short.MAX_VALUE)
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(8, 8, 8))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel4))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jTFName, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jBCgender, javax.swing.GroupLayout.Alignment.LEADING, 0, 304, Short.MAX_VALUE)
                                                                .addComponent(jTFUserame))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(btnDelete)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEdit))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnReset)))
                                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(jTFSearch))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTFUserame, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTFName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jBCgender, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jDCbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAdd)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEdit))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnReset)
                                        .addComponent(btnClear))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnTable.setPreferredSize(new java.awt.Dimension(710, 630));

        javax.swing.GroupLayout jPnTableLayout = new javax.swing.GroupLayout(jPnTable);
        jPnTable.setLayout(jPnTableLayout);
        jPnTableLayout.setHorizontalGroup(
                jPnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 710, Short.MAX_VALUE)
        );
        jPnTableLayout.setVerticalGroup(
                jPnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPnTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>

    private void jBCgenderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTFUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTFName.requestFocus();
        }
    }//GEN-LAST:event_jUsernameKeyReleased

    private void jTFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBCgender.requestFocus();
        }
    }//GEN-LAST:event_jUsernameKeyReleased

    private void jBCgenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jDCbirth.requestFocus();
        }
    }//GEN-LAST:event_jUsernameKeyReleased

    private void jDCbirthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTAadd.requestFocus();

        }
    }//GEN-LAST:event_jUsernameKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        addMinitry();
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        deleteMinitry();
    }

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        edit();
    }

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resetPass();
    }

    private void jTFSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {

        setClear();
        // TODO add your handling code here:
    }
    public void deleteMinitry(){
        int id=Integer.parseInt(labelId.getText());
        if(MinitryDAO.deleteMinitry(MinitryDAO.getInforMinitry(id))){
            JOptionPane.showMessageDialog(null, "Xóa thành công!");
            setData();
            setClear();
            return;
        }
        JOptionPane.showMessageDialog(null, "Xóa không thành công!");
        setClear();

    }
    public void setClear() {
        jTFSearch.setText("");
        jTFUserame.setText("");
        jTFName.setText("");
        jTAadd.setText("");
        jTFUserame.requestFocus();
        jBCgender.setSelectedIndex(0);
        jDCbirth.setCalendar(null);
        labelId.setText("");
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        btnReset.setEnabled(false);
    }

    public void edit() {
        String name = jTFName.getText();
        String username = jTFUserame.getText();
        java.util.Date date = jDCbirth.getDate();
        if(date==null){
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        Date date1 = new Date(date.getYear(), date.getMonth(), date.getDate());
        int gender = jBCgender.getSelectedIndex();
        String address = jTAadd.getText();
        if (name.length() == 0 || username.length() == 0 ||address.length() == 0) {
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        MinitryEntity minitry = MinitryDAO.getInforMinitry(Integer.parseInt(labelId.getText()));
        minitry.setUsername(username);
        minitry.setFullname(name);
        minitry.setBirthday(date1);
        minitry.setGender(gender);
        minitry.setAddress(address);
        MinitryEntity st1= MinitryDAO.getMinitrybyUsername(username);
        if(st1!=null){
            if(st1.getMinitryId()!= minitry.getMinitryId()){
                JOptionPane.showMessageDialog(null, "username trùng không thể thay đổi!");
                return;
            }
        }
        minitry.setUsername(username);
        if (MinitryDAO.updateMinitry(minitry)) {
            JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
            setData();
            setClear();
            return;
        }
        JOptionPane.showMessageDialog(null, "Cập nhật không thành công!");
        return;

    }

    public void resetPass() {
        String username = jTFUserame.getText();
        MinitryEntity minitryEntity = MinitryDAO.getMinitrybyUsername(username);
        minitryEntity.setPassword(username);
        if (MinitryDAO.updateMinitry(minitryEntity)) {
            JOptionPane.showMessageDialog(null, "Reset password thành công!");
            setData();
            setClear();
        } else {
            JOptionPane.showMessageDialog(null, "Reset password thất bại!");
        }

    }

    public void addMinitry() {
        String name = jTFName.getText();
        String username = jTFUserame.getText();
        java.util.Date date = jDCbirth.getDate();
        if(date==null){
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        Date date1 = new Date(date.getYear(), date.getMonth(), date.getDate());
        System.out.println(date.getYear());
        int gender = jBCgender.getSelectedIndex();
        String address = jTAadd.getText();
        if (name.length() == 0 || address.length() == 0) {
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        MinitryEntity minitry = new MinitryEntity();
        minitry.setUsername(username);
        minitry.setFullname(name);
        minitry.setPassword(username);
        minitry.setBirthday(date1);
        minitry.setGender(gender);
        minitry.setAddress(address);
        //minitry.setMinitryId(8);
        if (MinitryDAO.addMinitry(minitry)) {
            JOptionPane.showMessageDialog(null, "Thêm tài khoản giáo vụ thành công!");
            setData();
            setClear();
            return;
        }
        JOptionPane.showMessageDialog(null, "Trùng tài khoản giáo vụ. Vui lòng kiểm tra lại!");
        return;

    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> jBCgender;
    private javax.swing.JButton btnClear;
    private com.toedter.calendar.JDateChooser jDCbirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAadd;
    private javax.swing.JTextField jTFName;
    private javax.swing.JTextField jTFSearch;
    private javax.swing.JTextField jTFUserame;
    private javax.swing.JLabel labelId;

    // End of variables declaration
}
