/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.*;
import pojo.ClazzEntity;
import pojo.CourseEntity;
import pojo.SemesterEntity;
import pojo.SubjectEntity;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.util.List;
import controller.manageCourseController;

/**
 *
 * @author Xuyen
 */
public class jPnQLCourse extends javax.swing.JPanel {
    public static SemesterEntity current= null;

    /**
     * Creates new form jPnQLGV
     */
    public static String[] CBsubject=null;
    public static String[] CBteacher=new String[]{"Nguyễn Nguyễn","Lê Thị Lan","Nguyễn Văn","Ngô Văn A","Nguyễn Lan","Trần Anh Đào","Trần Huy","Lan Hương","Nguyễn Văn K","Nguyễn Văn M","Nguyễn Văn A","Nguyễn Văn B","Nguyễn Văn F"};
    public static String[] CBroom=new String[] { "E001", "E101", "E102", "E103", "E201", "E202", "E203", "F101", "F102", "F201", "F202", "G101", "G102", "G201", "G202", "G301", "G302" };

    public jPnQLCourse() {
        jPNQLRegistrationSession.setCurrentPeriod();
        current= jPNQLRegistrationSession.current;
        if(this.current==null){
            JOptionPane.showMessageDialog(null, "Vui lòng set học kì hiện tại!");
            return;
        }
        initComponents();
        labelId.setVisible(false);
        setSubjectList();
        setData();
    }
    void setData(){
        btnDelete.setEnabled(false);
        btnAdd.setEnabled(true);
        btnListDS.setEnabled(false);
        jCBsubject.requestFocus();
        manageCourseController controller=new manageCourseController(jPnTable,jTFSearch);
        controller.setField(btnDelete,btnListDS,jCBsubject,jCBteacher,jCBroom,jCBday,jCBperiod,jTFmaximum,jTFClass,labelId);
        controller.setDataToTableCourseofCurrentSemester();
    }
    void setClear(){
        jTFmaximum.setText("");
        jTFClass.setText("");
        btnDelete.setEnabled(false);
        btnListDS.setEnabled(false);
        jCBsubject.setSelectedIndex(0);
        jCBday.setSelectedIndex(0);
        jCBteacher.setSelectedIndex(0);
        jCBperiod.setSelectedIndex(0);
        jCBroom.setSelectedIndex(0);
    }
    void setSubjectList(){
        List<SubjectEntity> list= SubjectDAO.getSubjectList();
        CBsubject = new String[list.size()];
        int i = 0;
        for (SubjectEntity subject : list) {
            CBsubject[i]=subject.getSubjectname();
            i++;
        }
        jCBsubject.setModel(new javax.swing.DefaultComboBoxModel<>(CBsubject));
        jCBteacher.setModel(new javax.swing.DefaultComboBoxModel<>(CBteacher));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        jCBsubject = new javax.swing.JComboBox<>();
        jCBteacher = new javax.swing.JComboBox<>();
        jCBroom = new javax.swing.JComboBox<>();
        jCBday = new javax.swing.JComboBox<>();
        jCBperiod = new javax.swing.JComboBox<>();
        jTFmaximum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnListDS = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFClass = new javax.swing.JTextField();
        jPnTable = new javax.swing.JPanel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Môn học:");

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-search.png"))); // NOI18N

        jTFSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFSearch.setToolTipText("Tìm kiếm");
        jTFSearch.setMinimumSize(new java.awt.Dimension(10, 23));
        jTFSearch.setPreferredSize(new java.awt.Dimension(10, 23));
        jTFSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSearchActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("GVLT:");

        jCBsubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBsubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBsubjectKeyReleased(evt);
            }
        });

        jCBteacher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBteacherActionPerformed(evt);
            }
        });
        jCBteacher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBteacherKeyReleased(evt);
            }
        });

        jCBroom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBroom.setModel(new javax.swing.DefaultComboBoxModel<>(CBroom));
        jCBroom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBroomKeyReleased(evt);
            }
        });

        jCBday.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "CN" }));
        jCBday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBdayKeyReleased(evt);
            }
        });

        jCBperiod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBperiod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:30 - 9:30", "9:30 - 11:30", "13:30 - 15:30", "15:30 - 17:30" }));
        jCBperiod.setToolTipText("");
        jCBperiod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBperiodKeyReleased(evt);
            }
        });

        jTFmaximum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFmaximum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFmaximumKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Phòng học:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Thứ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ca:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Slot tối đa:");

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnListDS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListDS.setText("Xem danh sách SV");
        btnListDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListDSActionPerformed(evt);
            }
        });

        btnAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAll.setText("Tất cả HP");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Lớp:");

        jTFClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFClass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFClassKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(labelId))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnListDS)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnAll)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnDelete)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel3)
                                                                        .addGap(27, 27, 27))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(jLabel2))
                                                                        .addGap(13, 13, 13)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCBsubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBteacher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBroom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBday, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBperiod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTFmaximum)
                                                        .addComponent(jTFClass))))
                                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCBsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCBteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCBroom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCBday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCBperiod, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFmaximum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTFClass, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(btnClear))
                                .addGap(10, 10, 10)
                                .addComponent(labelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnListDS)
                                        .addComponent(btnAll))
                                .addGap(220, 220, 220))
        );

        jPnTable.setFocusTraversalPolicyProvider(true);
        jPnTable.setPreferredSize(new java.awt.Dimension(700, 630));

        javax.swing.GroupLayout jPnTableLayout = new javax.swing.GroupLayout(jPnTable);
        jPnTable.setLayout(jPnTableLayout);
        jPnTableLayout.setHorizontalGroup(
                jPnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 879, Short.MAX_VALUE)
        );
        jPnTableLayout.setVerticalGroup(
                jPnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 632, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPnTable, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPnTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
    }// </editor-fold>


    private void jTFSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setBtnAdd();
    }

    private void jCBteacherActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void jCBsubjectKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jCBteacher.requestFocus();
        }
    }

    private void jCBroomKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jCBday.requestFocus();
        }
    }

    private void jCBteacherKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jCBroom.requestFocus();
        }
    }

    private void jCBdayKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jCBperiod.requestFocus();
        }
    }

    private void jCBperiodKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jTFmaximum.requestFocus();
        }
    }

    private void jTFmaximumKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            jTFClass.requestFocus();
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        deleteCourse();
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setClear();
    }

    private void btnListDSActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        seeListCourse();
    }

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setData();
        setClear();
    }
    private void jTFClassKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
           // jTFClass.requestFocus();
            setBtnAdd();
        }
    }
    public void seeListCourse(){
        btnDelete.setEnabled(false);
        btnListDS.setEnabled(false);
        btnAdd.setEnabled(false);
        jCBsubject.requestFocus();
        manageCourseController controller=new manageCourseController(jPnTable,jTFSearch);
        //controller.setField(btnDelete,btnListDS,jCBsubject,jCBteacher,jCBroom,jCBday,jCBperiod,jTFmaximum,jTFClass,labelId);
        int id=Integer.parseInt(labelId.getText());
        controller.setDataToTableRegisteredCourse(id);
    }
    public void deleteCourse(){
        int id=Integer.parseInt(labelId.getText());
        if(CourseDAO.deleteCourse(CourseDAO.getCoursebyId(id))){
            JOptionPane.showMessageDialog(null, "Xóa thành công!");
            setData();
            setClear();
            return;
        }
        JOptionPane.showMessageDialog(null, "Xóa không thành công!");
        setClear();

    }
    void setBtnAdd(){
        String slot=jTFmaximum.getText();
        String className=jTFClass.getText();
        boolean isNumeric = (slot != null && slot.matches("[0-9]+"));
        if(slot.length()==0||className.length()==0){
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        if (!isNumeric) {
            JOptionPane.showMessageDialog(null, "Slot là số!");
            return;
        }
        int slotmax=Integer.parseInt(slot);
        if(slotmax<30||slotmax>200){
            JOptionPane.showMessageDialog(null, "Slot là số >= 30 và <= 200!");
            return;
        }
        String subject=CBsubject[jCBsubject.getSelectedIndex()];
        String teacher=CBteacher[jCBteacher.getSelectedIndex()];
        String room=CBroom[jCBroom.getSelectedIndex()];
        int period=jCBperiod.getSelectedIndex()+1;
        int day=jCBday.getSelectedIndex()+2;
        SubjectEntity sub=SubjectDAO.getSujectbyName(subject);
        CourseEntity course=new CourseEntity();
        course.setSemester(current);
        course.setCoursename(subject+" - "+className);
        course.setMaximum(slotmax);
        course.setTeacher(teacher);
        course.setDay(day);
        course.setRoom(room);
        course.setPeriod(period);
        course.setSubject(sub);
        if(CourseDAO.addCourse(course)){
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            setData();
            setClear();
            return;
        }
        JOptionPane.showMessageDialog(null, "Trùng khóa học!");
        return;


    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnListDS;
    private javax.swing.JComboBox<String> jCBday;
    private javax.swing.JComboBox<String> jCBperiod;
    private javax.swing.JComboBox<String> jCBroom;
    private javax.swing.JComboBox<String> jCBsubject;
    private javax.swing.JComboBox<String> jCBteacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnTable;
    private javax.swing.JTextField jTFClass;
    private javax.swing.JTextField jTFSearch;
    private javax.swing.JTextField jTFmaximum;
    private javax.swing.JLabel labelId;
}
