/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.ManagementStudentListController;
import controller.StudentController;
import dao.ClassDAO;
import dao.MinitryDAO;
import dao.StudentDAO;
import pojo.ClazzEntity;
import pojo.MinitryEntity;
import pojo.StudentEntity;

import javax.swing.*;
import java.sql.Date;
import java.util.List;

/**
 * @author Xuyen
 */
public class jPnQLStudent extends javax.swing.JPanel {

    /**
     * Creates new form jPnQLGV
     */
    public String[] CBclass = null;

    public jPnQLStudent() {
        initComponents();
        setClassList();
        setData();
    }
    public void setClassList(){
        List<ClazzEntity> Classlist = ClassDAO.getClassList();
        CBclass = new String[Classlist.size()];
        int i = 0;
        for (ClazzEntity classs : Classlist) {
            CBclass[i] = classs.getClassname();
            i++;
        }
        jCBclass.setModel(new javax.swing.DefaultComboBoxModel<>(CBclass));
    }
    public void setData() {
        jTFUserame.setEnabled(false);
        btnReset.setEnabled(false);
        btnEdit.setEnabled(false);
        ManagementStudentListController controller = new ManagementStudentListController(jPnTable, jTFSearch);
        controller.setField(btnFind, btnReset, btnEdit, jTFUserame, jTFName, jBCgender, jTAadd, jDCbirth, labelId, jTFmssv, jCBclass, jTASubject);
        controller.setDataToTableStudent(CBclass);
        jTFName.requestFocus();
        labelId.setText("");
        jTASubject.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        labelId=new JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAadd = new javax.swing.JTextArea();
        jTFUserame = new javax.swing.JTextField();
        jTFName = new javax.swing.JTextField();
        jBCgender = new javax.swing.JComboBox<>();
        jDCbirth = new com.toedter.calendar.JDateChooser();
        btnAdd = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFSearch = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFmssv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCBclass = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTASubject = new javax.swing.JTextArea();
        btnSee = new javax.swing.JButton();
        jPnTable = new javax.swing.JPanel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Giới tính:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        jTAadd.setColumns(20);
        jTAadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTAadd.setRows(5);
        jScrollPane1.setViewportView(jTAadd);
        jTAadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTAaddKeyReleased(evt);
            }
        });


        jTFUserame.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFUserame.setToolTipText("");
        jTFUserame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFUsernameKeyReleased(evt);
            }
        });


        jTFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNameKeyReleased(evt);
            }
        });

        jBCgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));
        jBCgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCgenderActionPerformed(evt);
            }
        });
        jBCgender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBCgenderKeyReleased(evt);
            }
        });


        jDCbirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDCbirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDCbirthKeyReleased(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnFind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-search.png"))); // NOI18N
        btnFind.setText("Tìm kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("Cập nhật");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rotate-left-circular-arrow-interface-symbol.png"))); // NOI18N
        btnReset.setText("Reset pass");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-search.png"))); // NOI18N

        jTFSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFSearch.setToolTipText("Tìm kiếm");
        jTFSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSearchActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("MSSV:");

        jTFmssv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFmssv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFmssvKeyReleased(evt);
            }
        });


        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Lớp:");

        jCBclass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Môn học:");

        jTASubject.setColumns(20);
        jTASubject.setRows(10);
        jTASubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        //jTASubject.setPreferredSize(new java.awt.Dimension(164, 64));
        jScrollPane2.setViewportView(jTASubject);

        btnSee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSee.setText("Xem tất cả");
        btnSee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnFind)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnEdit))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel7)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel3))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel6)
                                                                                        .addComponent(jLabel5)
                                                                                        .addComponent(jLabel8)))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(jLabel1)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(jTFSearch))
                                                                                .addComponent(jTFName)
                                                                                .addComponent(jBCgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jTFmssv, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jTFUserame)
                                                                                .addComponent(jDCbirth, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                                                                .addComponent(jCBclass, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnReset)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnSee)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jTFUserame, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTFName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTFmssv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jBCgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(45, 45, 45)))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jDCbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCBclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAdd)
                                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSee)
                                        .addComponent(btnReset)
                                        .addComponent(btnClear))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnTable.setFocusTraversalPolicyProvider(true);
        jPnTable.setPreferredSize(new java.awt.Dimension(700, 630));

        javax.swing.GroupLayout jPnTableLayout = new javax.swing.GroupLayout(jPnTable);
        jPnTable.setLayout(jPnTableLayout);
        jPnTableLayout.setHorizontalGroup(
                jPnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 838, Short.MAX_VALUE)
        );
        jPnTableLayout.setVerticalGroup(
                jPnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPnTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        addStudent();
    }

    private void btnSeeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setData();
    }
    private void jTFSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        resetPass();
    }

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        edit();
    }

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        findStudentbyClass();

    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setClear();
    }

    private void jBCgenderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void jTFUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTFName.requestFocus();
        }
    }

    private void jTFNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTFmssv.requestFocus();
        }
    }

    private void jTFmssvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jBCgender.requestFocus();
        }
    }

    private void jBCgenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jDCbirth.requestFocus();
        }
    }

    private void jDCbirthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTAadd.requestFocus();
        }
    }

    private void jTAaddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jCBclass.requestFocus();
        }
    }
    public void findStudentbyClass(){
        String clazz=CBclass[jCBclass.getSelectedIndex()];
        ManagementStudentListController controller = new ManagementStudentListController(jPnTable, jTFSearch);
        controller.setDatatoTableStudentbyClass(clazz,CBclass);
        controller.setField(btnFind, btnReset, btnEdit, jTFUserame, jTFName, jBCgender, jTAadd, jDCbirth, labelId, jTFmssv, jCBclass, jTASubject);

    }
   /* public void deleteStudent() {
        int id = Integer.parseInt(labelId.getText());
        if (StudentDAO.deleteStudent(StudentDAO.getStudentbyId(id))) {
            JOptionPane.showMessageDialog(null, "Xóa thành công!");
            setData();
            return;
        }
        JOptionPane.showMessageDialog(null, "Xóa không thành công!");

    }*/

    public void setClear() {
        jTFSearch.setText("");
        jTFUserame.setText("");
        jTFName.setText("");
        jTAadd.setText("");
        jTFUserame.requestFocus();
        jBCgender.setSelectedIndex(0);
        jDCbirth.setCalendar(null);
        jCBclass.setSelectedIndex(0);
        jTFmssv.setText("");
        jTASubject.setText("");
        jTFUserame.setEnabled(false);
        btnReset.setEnabled(false);
        btnEdit.setEnabled(false);
    }

    public void edit() {
        String mssv = jTFmssv.getText();
        String name = jTFName.getText();
        String username = jTFUserame.getText();
        java.util.Date date = jDCbirth.getDate();
        if (date == null) {
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        Date date1 = new Date(date.getYear(), date.getMonth(), date.getDate());
        int gender = jBCgender.getSelectedIndex();
        String address = jTAadd.getText();
        if (name.length() == 0 || username.length() == 0 || address.length() == 0 || mssv.length() == 0) {
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        StudentEntity minitry = StudentDAO.getStudentbyId(Integer.parseInt(labelId.getText()));
        minitry.setMssv(mssv);
        minitry.setFullname(name);
        minitry.setBirthday(date1);
        minitry.setGender(gender);
        minitry.setAddress(address);
        StudentEntity st1=StudentDAO.getStudentbyUsername(mssv);
        if(st1!=null){
            if(st1.getStudentId()!= minitry.getStudentId()){
                JOptionPane.showMessageDialog(null, "MSSV trùng không thể thay đổi!");
                return;
            }
        }
        minitry.setUsername(mssv);
        int index = jCBclass.getSelectedIndex();
        ClazzEntity cl = ClassDAO.getClassbyClassname(CBclass[index]);
        minitry.setClasss(cl);
        if (StudentDAO.updateStudent(minitry)) {
            JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
            setData();
            setClear();
            return;
        }
        JOptionPane.showMessageDialog(null, "Cập nhật không thành công!");
        return;

    }

    public void resetPass() {
        int id = Integer.parseInt(labelId.getText());
        StudentEntity st = StudentDAO.getStudentbyId(id);
        st.setPassword(st.getUsername());
        if (StudentDAO.updateStudent(st)) {
            JOptionPane.showMessageDialog(null, "Reset password thành công!");
            setData();
            setClear();
        } else {
            JOptionPane.showMessageDialog(null, "Reset password thất bại!");
        }

    }

    public void addStudent() {
        String mssv = jTFmssv.getText();
        String name = jTFName.getText();
        //String username = jTFUserame.getText();
        java.util.Date date = jDCbirth.getDate();
        if (date == null) {
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        Date date1 = new Date(date.getYear(), date.getMonth(), date.getDate());
        System.out.println(date.getYear());
        int gender = jBCgender.getSelectedIndex();
        String address = jTAadd.getText();
        if (name.length() == 0 || address.length() == 0||mssv.length()==0) {
            JOptionPane.showMessageDialog(null, "Không để trống!");
            return;
        }
        int index= jCBclass.getSelectedIndex();
        ClazzEntity cl=ClassDAO.getClassbyClassname(CBclass[index]);

        StudentEntity minitry = new StudentEntity();
        minitry.setMssv(mssv);
        minitry.setUsername(mssv);
        minitry.setFullname(name);
        minitry.setPassword(mssv);
        minitry.setBirthday(date1);
        minitry.setGender(gender);
        minitry.setAddress(address);
        minitry.setClasss(cl);
        if (StudentDAO.addStudent(minitry)) {
            JOptionPane.showMessageDialog(null, "Thêm tài khoản thành công!");
            setData();
            setClear();
            return;
        }
        JOptionPane.showMessageDialog(null, "Trùng tài khoản. Vui lòng kiểm tra lại!");
        return;

    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSee;
    private javax.swing.JComboBox<String> jBCgender;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> jCBclass;
    private com.toedter.calendar.JDateChooser jDCbirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTASubject;
    private javax.swing.JTextArea jTAadd;
    private javax.swing.JTextField jTFName;
    private javax.swing.JTextField jTFSearch;
    private javax.swing.JTextField jTFUserame;
    private javax.swing.JTextField jTFmssv;
    private JLabel labelId;
    // End of variables declaration                   
}
